apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: wordpress
 annotations:
   volume.beta.kubernetes.io/storage-class: "ebs-ssd"  
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 2Gi
---     
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: makanab/docker-wordpress-nginx:1.6
        name: wordpress
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-password.txt        
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-pass
              key: wp-password.txt                      
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/www        
      volumes:
      - name: nginx
        persistentVolumeClaim:
          claimName: wordpress          