apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs-ssd"  
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol2
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs-ssd"  
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi          
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol3
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs-ssd"  
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi    persistentVolumeReclaimPolicy: Retain